### ISSUE TITLE
creating new app error

### ISSUE THREAD

**Issue by gmchaturvedi1** [HumbleSpark/sambell#4]
when i run the  following command :

sambell new app

the following erro is coming:

 sudo sambell new clientapp
/usr/lib/node_modules/sambell/bin/sambell.js:35
      );
      ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

kindly suggest.

regards
gmchaturvedi

**Comment by ndreckshage** [comment]
sorry for late reply, didnt see notification. closing as i believe this is node version. would recommend using node 8
